version: '3.7'

services:
  mongodb:
    image: mongo:6.0-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
